// GENERATED by scripts/gen_verse_display_fixtures.py from the engine's usfm_verse.lift_verse
// (#91 Phase 2b). Each entry is exactly the `display` payload the engine sends
// for that raw verse string. Regenerate rather than hand-edit:
//   python scripts/gen_verse_display_fixtures.py engine src/lib/components/__tests__/verseDisplayFixtures.ts
import type { VerseDisplay } from "../../types/finding";
import { identityDisplay } from "../../utils/verseDisplay";

export const DISPLAY_FIXTURES: Record<string, VerseDisplay> = {
  ["\\it मुझे इस बात का भरोसा है\\it*\\f + \\fr 1.6 \\fq मुझे इस बात का भरोसा है: \\ft इसका मतलब यह है पौलुस ने जो कुछ कहा उसका सच पूरी तरह से आश्वस्त था।\\f* कि जिसने तुम में अच्छा काम आरम्भ किया है।"]: {"plain": "मुझे इस बात का भरोसा है कि जिसने तुम में अच्छा काम आरम्भ किया है।", "notes": [{"kind": "footnote", "caller": "+", "reference": "1.6", "parts": [{"marker": "fr", "text": "1.6"}, {"marker": "fq", "text": "मुझे इस बात का भरोसा है:"}, {"marker": "ft", "text": "इसका मतलब यह है पौलुस ने जो कुछ कहा उसका सच पूरी तरह से आश्वस्त था।"}], "text": "मुझे इस बात का भरोसा है: इसका मतलब यह है पौलुस ने जो कुछ कहा उसका सच पूरी तरह से आश्वस्त था।", "position": 23}], "removed": [[0, 4], [27, 147]], "styles": [{"marker": "it", "start": 0, "end": 23}], "warnings": []},
  ["पवित्र लोगों\\x + \\xo 1.1 \\xt रोम. 1:7\\x* के नाम"]: {"plain": "पवित्र लोगों के नाम", "notes": [{"kind": "xref", "caller": "+", "reference": "1.1", "parts": [{"marker": "xo", "text": "1.1"}, {"marker": "xt", "text": "रोम. 1:7"}], "text": "रोम. 1:7", "position": 12}], "removed": [[12, 40]], "styles": [], "warnings": []},
  ["a\\f + \\ft one\\f* b\\f + \\ft two\\f*"]: {"plain": "a b", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "one"}], "text": "one", "position": 1}, {"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "two"}], "text": "two", "position": 3}], "removed": [[1, 16], [18, 33]], "styles": [], "warnings": []},
  ["a\\f + \\ft first note\\f* b\\f + \\ft second note\\f*"]: {"plain": "a b", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "first note"}], "text": "first note", "position": 1}, {"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "second note"}], "text": "second note", "position": 3}], "removed": [[1, 23], [25, 48]], "styles": [], "warnings": []},
  ["அவன் சொன்னான்\\f + \\ft குறிப்பு\\f* அந்த காகம் பறந்தது."]: {"plain": "அவன் சொன்னான் அந்த காகம் பறந்தது.", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "குறிப்பு"}], "text": "குறிப்பு", "position": 13}], "removed": [[13, 33]], "styles": [], "warnings": []},
  ["a \\f + \\ft n\\f* b"]: {"plain": "a b", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "n"}], "text": "n", "position": 2}], "removed": [[2, 16]], "styles": [], "warnings": []},
  ["a\\f + \\ft n\\f* b"]: {"plain": "a b", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "n"}], "text": "n", "position": 1}], "removed": [[1, 14]], "styles": [], "warnings": []},
  ["a \\f + \\ft n\\f*"]: {"plain": "a ", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "n"}], "text": "n", "position": 2}], "removed": [[2, 15]], "styles": [], "warnings": []},
  ["a\\f + \\ft n\\f*"]: {"plain": "a", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "n"}], "text": "n", "position": 1}], "removed": [[1, 14]], "styles": [], "warnings": []},
  ["\\f + \\ft n\\f* b"]: {"plain": "b", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "n"}], "text": "n", "position": 0}], "removed": [[0, 14]], "styles": [], "warnings": []},
  ["a \\x - \\xo 1.1 \\xt Gen 1.1\\x* b"]: {"plain": "a b", "notes": [{"kind": "xref", "caller": "-", "reference": "1.1", "parts": [{"marker": "xo", "text": "1.1"}, {"marker": "xt", "text": "Gen 1.1"}], "text": "Gen 1.1", "position": 2}], "removed": [[2, 30]], "styles": [], "warnings": []},
  ["இந்த \\f + \\ft குறிப்பு\\f* நற்கிரியையை"]: {"plain": "இந்த நற்கிரியையை", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "குறிப்பு"}], "text": "குறிப்பு", "position": 5}], "removed": [[5, 26]], "styles": [], "warnings": []},
  ["a \\f + \\ft inside\\f* b"]: {"plain": "a b", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "inside"}], "text": "inside", "position": 2}], "removed": [[2, 21]], "styles": [], "warnings": []},
  ["the \\nd Lord\\nd*, \\wj said \\+it so\\+it* to him\\wj*."]: {"plain": "the Lord, said so to him.", "notes": [], "removed": [[4, 8], [12, 16], [18, 22], [27, 32], [34, 39], [46, 50]], "styles": [{"marker": "nd", "start": 4, "end": 8}, {"marker": "wj", "start": 10, "end": 24}, {"marker": "it", "start": 15, "end": 17}], "warnings": []},
  ["alpha\\f + \\ft n\\f* bravo"]: {"plain": "alpha bravo", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "n"}], "text": "n", "position": 5}], "removed": [[5, 18]], "styles": [], "warnings": []},
  ["\\f + \\ft n\\f*alpha"]: {"plain": "alpha", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "n"}], "text": "n", "position": 0}], "removed": [[0, 13]], "styles": [], "warnings": []},
  ["alpha\\f + \\ft n\\f*"]: {"plain": "alpha", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "n"}], "text": "n", "position": 5}], "removed": [[5, 18]], "styles": [], "warnings": []},
  ["a\\f + \\ft one\\f*b\\x + \\xt G 1:1\\x*c"]: {"plain": "abc", "notes": [{"kind": "footnote", "caller": "+", "reference": "", "parts": [{"marker": "ft", "text": "one"}], "text": "one", "position": 1}, {"kind": "xref", "caller": "+", "reference": "", "parts": [{"marker": "xt", "text": "G 1:1"}], "text": "G 1:1", "position": 2}], "removed": [[1, 16], [17, 34]], "styles": [], "warnings": []},
};

/** The engine's display for a seeded raw string, or the identity display for a
 *  string with no markup (what the component falls back to anyway). */
export function displayFor(raw: string): VerseDisplay {
  return DISPLAY_FIXTURES[raw] ?? identityDisplay(raw);
}
