"""Emit src/lib/components/__tests__/verseDisplayFixtures.ts from the engine's own
fragment reader, so the frontend tests seed exactly what the engine sends (#91 Phase 2b).

    python scripts/gen_verse_display_fixtures.py engine src/lib/components/__tests__/verseDisplayFixtures.ts

Add a raw string to RAW when a frontend test seeds a new verse with markup; never
hand-edit the output."""
import json
import sys
from pathlib import Path

ENGINE = Path(sys.argv[1])
OUT = Path(sys.argv[2])
sys.path.insert(0, str(ENGINE))
from tc_ai_bridge.usfm_verse import lift_verse  # noqa: E402

RAW = [
    # VerseList.test.ts PHP_1_6 (Hindi, \it + footnote) -- also usfmNotes.test.ts
    "\\it मुझे इस बात का भरोसा है\\it*\\f + \\fr 1.6 \\fq मुझे इस बात का भरोसा है: "
    "\\ft इसका मतलब यह है पौलुस ने जो कुछ कहा उसका सच पूरी तरह से आश्वस्त था।\\f* "
    "कि जिसने तुम में अच्छा काम आरम्भ किया है।",
    "पवित्र लोगों\\x + \\xo 1.1 \\xt रोम. 1:7\\x* के नाम",
    "a\\f + \\ft one\\f* b\\f + \\ft two\\f*",
    "a\\f + \\ft first note\\f* b\\f + \\ft second note\\f*",
    "அவன் சொன்னான்\\f + \\ft குறிப்பு\\f* அந்த காகம் பறந்தது.",
    # usfmNotes.test.ts mapping cases
    "a \\f + \\ft n\\f* b",
    "a\\f + \\ft n\\f* b",
    "a \\f + \\ft n\\f*",
    "a\\f + \\ft n\\f*",
    "\\f + \\ft n\\f* b",
    "a \\x - \\xo 1.1 \\xt Gen 1.1\\x* b",
    "இந்த \\f + \\ft குறிப்பு\\f* நற்கிரியையை",
    "a \\f + \\ft inside\\f* b",
    "the \\nd Lord\\nd*, \\wj said \\+it so\\+it* to him\\wj*.",
    # usfmNotes.test.ts withNoteMarkers layout cases
    "alpha\\f + \\ft n\\f* bravo",
    "\\f + \\ft n\\f*alpha",
    "alpha\\f + \\ft n\\f*",
    "a\\f + \\ft one\\f*b\\x + \\xt G 1:1\\x*c",
]

entries = []
for raw in RAW:
    payload = lift_verse(raw).to_dict()
    entries.append(f"  [{json.dumps(raw, ensure_ascii=False)}]: {json.dumps(payload, ensure_ascii=False)},")

header = '''// GENERATED by scripts/gen_verse_display_fixtures.py from the engine's usfm_verse.lift_verse
// (#91 Phase 2b). Each entry is exactly the `display` payload the engine sends
// for that raw verse string. Regenerate rather than hand-edit:
//   python scripts/gen_verse_display_fixtures.py engine src/lib/components/__tests__/verseDisplayFixtures.ts
import type { VerseDisplay } from "../../types/finding";
import { identityDisplay } from "../../utils/verseDisplay";

export const DISPLAY_FIXTURES: Record<string, VerseDisplay> = {
'''
footer = '''};

/** The engine's display for a seeded raw string, or the identity display for a
 *  string with no markup (what the component falls back to anyway). */
export function displayFor(raw: string): VerseDisplay {
  return DISPLAY_FIXTURES[raw] ?? identityDisplay(raw);
}
'''
OUT.write_text(header + "\n".join(entries) + "\n" + footer, encoding="utf-8", newline="\n")
print(f"wrote {OUT} with {len(entries)} fixtures")
